/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ListaDeTareas;

import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Gabriel
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarTabla();
        cargarPrioridades();
        
    }
    
    private void cargarPrioridades() {
        comboPrioridad.removeAllItems();
        comboPrioridad.addItem("1 (Alta)");
        comboPrioridad.addItem("2");
        comboPrioridad.addItem("3");
        comboPrioridad.addItem("4");
        comboPrioridad.addItem("5 (Baja)");
    }
    
    private void cargarTabla() {
        List<Tarea> tareas = TareaManager.cargarTareas();

        String[] columnas = {"Nombre", "Prioridad", "Completada"};
        Object[][] datos = new Object[tareas.size()][3];

        
        
        for (int i = 0; i < tareas.size(); i++) {
            Tarea t = tareas.get(i);
            datos[i][0] = t.getNombre();
            datos[i][1] = t.getPrioridad();
            datos[i][2] = t.isCompletada() ? "Sí" : "No";
        }
        
        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            columnas
        ));
        tablaTareas.setBackground(Color.decode("#FDF9F6"));
        tablaTareas.setForeground(Color.decode("#4E342E"));
        tablaTareas.setGridColor(Color.decode("#BCAAA4"));

        tablaTareas.setSelectionBackground(Color.decode("#EDE0D4"));
        tablaTareas.setSelectionForeground(Color.decode("#3E2723"));

        JTableHeader header = tablaTareas.getTableHeader();
        header.setBackground(Color.decode("#D7CCC8"));
        header.setForeground(Color.decode("#3E2723"));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        delete1 = new javax.swing.JButton();
        bg2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        chkCompletada = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        comboPrioridad = new javax.swing.JComboBox<>();
        tituloCreacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1010, 720));

        bg.setBackground(new java.awt.Color(248, 244, 239));
        bg.setPreferredSize(new java.awt.Dimension(1010, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(215, 204, 200));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 39, 35));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAREAS");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 80));

        btnComplete.setBackground(new java.awt.Color(93, 64, 55));
        btnComplete.setForeground(new java.awt.Color(255, 255, 255));
        btnComplete.setText("Completada");
        btnComplete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        bg.add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        tablaTareas.setBackground(new java.awt.Color(253, 249, 246));
        tablaTareas.setForeground(new java.awt.Color(78, 52, 46));
        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTareas.setGridColor(new java.awt.Color(188, 170, 164));
        tablaTareas.setSelectionBackground(new java.awt.Color(237, 224, 212));
        tablaTareas.setSelectionForeground(new java.awt.Color(62, 39, 35));
        jScrollPane2.setViewportView(tablaTareas);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        delete1.setBackground(new java.awt.Color(93, 64, 55));
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("Eliminar");
        delete1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        bg.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        bg2.setBackground(new java.awt.Color(237, 224, 212));

        txtNombre.setToolTipText("");
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        chkCompletada.setBackground(new java.awt.Color(255, 255, 255));
        chkCompletada.setText("Completa");
        chkCompletada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chkCompletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompletadaActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(93, 64, 55));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPrioridad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrioridadActionPerformed(evt);
            }
        });

        tituloCreacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloCreacion.setForeground(new java.awt.Color(62, 39, 35));
        tituloCreacion.setText("Creacion de Tareas");

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCreacion)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkCompletada))
                    .addComponent(btnGuardar))
                .addGap(80, 80, 80))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(tituloCreacion)
                .addGap(8, 8, 8)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCompletada))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        bg.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, 640));

        jPanel2.setBackground(new java.awt.Color(215, 204, 200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombre.getText();
        String seleccion = (String) comboPrioridad.getSelectedItem();
        int prioridad = Integer.parseInt(seleccion.substring(0, 1));
        boolean completada = chkCompletada.isSelected();

        Tarea tarea = new Tarea(nombre, prioridad, completada);

        try {
            TareaManager.agregarTarea(tarea);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNombre.setText("");
        cargarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        int filaSeleccionada = tablaTareas.getSelectedRow();

        if (filaSeleccionada != -1) {
            try {
                TareaManager.marcarCompletadaIndice(filaSeleccionada);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una tarea de la tabla.");
    }   
        cargarTabla();
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void chkCompletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompletadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCompletadaActionPerformed

    private void comboPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrioridadActionPerformed
        
    }//GEN-LAST:event_comboPrioridadActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        int filaSeleccionada = tablaTareas.getSelectedRow();
        
        try {
            TareaManager.eliminarTareaIndice(filaSeleccionada);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        cargarTabla();
    }//GEN-LAST:event_delete1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkCompletada;
    private javax.swing.JComboBox<String> comboPrioridad;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTareas;
    private javax.swing.JLabel tituloCreacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
