/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.seitasks.Menu;

import Diccionario.Diccionario;
import ListaDeTareas.MainTareas;
import com.seitasks.FlashCards.MainCards;
import com.seitasks.Pomodoro.MainPomodoro;
import com.seitasks.encuesta.GraficadorBarras;
import com.seitasks.encuesta.GraficasTorta;
import com.seitasks.encuesta.LectorEncuesta;
import com.seitasks.encuesta.RespuestaEncuesta;

/**
 *
 * @author Nicolas Marin
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonEstadisticas = new javax.swing.JButton();
        BotonCards = new javax.swing.JButton();
        BotonLista = new javax.swing.JButton();
        BotonPomodoro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        BotonEstadisticas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonEstadisticas.setText("Estadisticas");
        BotonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadisticasActionPerformed(evt);
            }
        });

        BotonCards.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonCards.setText("Cards");
        BotonCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCardsActionPerformed(evt);
            }
        });

        BotonLista.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonLista.setText("Lista");
        BotonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaActionPerformed(evt);
            }
        });

        BotonPomodoro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonPomodoro.setText("Pomodoro");
        BotonPomodoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPomodoroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        jButton1.setFont(BotonEstadisticas.getFont());
        jButton1.setText("Diccionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEstadisticas)
                    .addComponent(jButton1)
                    .addComponent(BotonCards)
                    .addComponent(BotonLista)
                    .addComponent(BotonPomodoro)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BotonPomodoro)
                .addGap(18, 18, 18)
                .addComponent(BotonLista)
                .addGap(18, 18, 18)
                .addComponent(BotonCards)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(BotonEstadisticas)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadisticasActionPerformed
        java.util.List<RespuestaEncuesta> resultados = LectorEncuesta.leerResultados();
        System.out.println(resultados);
        GraficadorBarras.mostrarGraficoBarras(resultados);
        GraficasTorta.mostrarGraficas(resultados);
    }//GEN-LAST:event_BotonEstadisticasActionPerformed

    private void BotonPomodoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPomodoroActionPerformed
        MainPomodoro.main();
    }//GEN-LAST:event_BotonPomodoroActionPerformed

    private void BotonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaActionPerformed
        MainTareas.main();
    }//GEN-LAST:event_BotonListaActionPerformed

    private void BotonCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCardsActionPerformed
        MainCards.main();
    }//GEN-LAST:event_BotonCardsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Diccionario.main();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCards;
    private javax.swing.JButton BotonEstadisticas;
    private javax.swing.JButton BotonLista;
    private javax.swing.JButton BotonPomodoro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
