/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.seitasks.Menu;

import com.seitasks.FlashCards.MainCards;
import com.seitasks.Pomodoro.MainPomodoro;
import com.seitasks.encuesta.GraficadorBarras;
import com.seitasks.encuesta.GraficasTorta;
import com.seitasks.encuesta.LectorEncuesta;
import com.seitasks.encuesta.RespuestaEncuesta;

/**
 *
 * @author Nicolas Marin
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonEstadisticas = new javax.swing.JButton();
        BotonCards = new javax.swing.JButton();
        BotonLista = new javax.swing.JButton();
        BotonPomodoro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        BotonEstadisticas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonEstadisticas.setText("Estadisticas");
        BotonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadisticasActionPerformed(evt);
            }
        });

        BotonCards.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonCards.setText("Cards");
        BotonCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCardsActionPerformed(evt);
            }
        });

        BotonLista.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonLista.setText("Lista");
        BotonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaActionPerformed(evt);
            }
        });

        BotonPomodoro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonPomodoro.setText("Pomodoro");
        BotonPomodoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPomodoroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonPomodoro)
                    .addComponent(BotonLista)
                    .addComponent(BotonCards)
                    .addComponent(BotonEstadisticas)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BotonPomodoro)
                .addGap(18, 18, 18)
                .addComponent(BotonLista)
                .addGap(18, 18, 18)
                .addComponent(BotonCards)
                .addGap(18, 18, 18)
                .addComponent(BotonEstadisticas)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadisticasActionPerformed
        java.util.List<RespuestaEncuesta> resultados = LectorEncuesta.leerResultados();
        System.out.println(resultados);
        GraficadorBarras.mostrarGraficoBarras(resultados);
        GraficasTorta.mostrarGraficas(resultados);
    }//GEN-LAST:event_BotonEstadisticasActionPerformed

    private void BotonPomodoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPomodoroActionPerformed
        MainPomodoro.main();
    }//GEN-LAST:event_BotonPomodoroActionPerformed

    private void BotonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaActionPerformed
        MainTareas.main();
    }//GEN-LAST:event_BotonListaActionPerformed

    private void BotonCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCardsActionPerformed
        MainCards.main();
    }//GEN-LAST:event_BotonCardsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCards;
    private javax.swing.JButton BotonEstadisticas;
    private javax.swing.JButton BotonLista;
    private javax.swing.JButton BotonPomodoro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
