/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.seitasks.Pomodoro;

import javax.swing.*;
import com.seitasks.encuesta.MainEncuesta;
import java.awt.event.ActionEvent;
public class Pomodoro extends javax.swing.JPanel {

    private javax.swing.Timer timer;
    private int tiempoRestante; // en segundos
    private boolean enEjecucion;
    private boolean modoEstudio = true;
    
    
    public Pomodoro() {
        initComponents();
        configurarComponentes();
        configurarTemporizador();
        configurarTiempoInicial();
        actualizarTiempoDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpinnerEstudio = new javax.swing.JSpinner();
        labelEstudio = new javax.swing.JLabel();
        labelDescanso = new javax.swing.JLabel();
        spinnerDescanso = new javax.swing.JSpinner();
        btnCambiarModo = new javax.swing.JButton();
        labelTiempo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(248, 244, 239));
        setMaximumSize(new java.awt.Dimension(1010, 720));
        setMinimumSize(new java.awt.Dimension(1010, 720));
        setPreferredSize(new java.awt.Dimension(1010, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(SpinnerEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        labelEstudio.setBackground(new java.awt.Color(255, 51, 51));
        labelEstudio.setText("Estudio(min): ");
        add(labelEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        labelDescanso.setText("Descanso(Min): ");
        add(labelDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));
        add(spinnerDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        btnCambiarModo.setText("Cambiar a descanso");
        btnCambiarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarModoActionPerformed(evt);
            }
        });
        add(btnCambiarModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        labelTiempo.setBackground(new java.awt.Color(255, 51, 102));
        labelTiempo.setFont(new java.awt.Font("Dialog", 0, 72)); // NOI18N
        labelTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTiempo.setText("60:00");
        add(labelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 220, 74));

        btnIniciar.setText("Iniciar");
        add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        btnPausar.setText("Pausar");
        add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        btnReiniciar.setText("Reiniciar");
        add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(237, 224, 212));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 581, 1010, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarModoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int response = JOptionPane.showConfirmDialog(
            this,
            "¿Quieres registrar tu sesión?",
            "Registrar Sesión",
            JOptionPane.YES_NO_OPTION
        );
        
        if (response == JOptionPane.YES_OPTION) {
            MainEncuesta.main(0);
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        } else if (response == JOptionPane.NO_OPTION) {
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    

    private void configurarComponentes() {
        SpinnerEstudio.setModel(new SpinnerNumberModel(60, 1, 120, 1)); 
        spinnerDescanso.setModel(new SpinnerNumberModel(20, 1, 60, 1)); 

        
        btnCambiarModo.addActionListener(this::cambiarModo);

        
        btnIniciar.addActionListener(this::iniciarTemporizador);
        btnPausar.addActionListener(this::pausarTemporizador);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(this::reiniciarTemporizador);

        btnPausar.setEnabled(false);
    }

    private void configurarTemporizador() {
        timer = new Timer(1000, e -> {
            if (tiempoRestante > 0) {
                tiempoRestante--;
                actualizarTiempoDisplay();
            } else {
                finalizarPeriodo();
            }
        });
    }

    private void iniciarTemporizador(ActionEvent evt) {
        if (!enEjecucion) {
            timer.start();
            enEjecucion = true;
            btnIniciar.setEnabled(false);
            btnPausar.setEnabled(true);
        }
    }

    private void pausarTemporizador(ActionEvent evt) {
        if (enEjecucion) {
            timer.stop();
            enEjecucion = false;
            btnIniciar.setEnabled(true);
            btnPausar.setEnabled(false);
        }
    }

    private void reiniciarTemporizador(ActionEvent evt) {
        timer.stop();
        enEjecucion = false;
        configurarTiempoInicial();
        actualizarTiempoDisplay();
        btnIniciar.setEnabled(true);
        btnPausar.setEnabled(false);
    }

    private void cambiarModo(ActionEvent evt) {
        modoEstudio = !modoEstudio;
        configurarTiempoInicial();
        actualizarTiempoDisplay();
        btnCambiarModo.setText(modoEstudio ? "Cambiar a descanso" : "Cambiar a estudio");
    }

    private void configurarTiempoInicial() {
        int minutos = modoEstudio ? (int) SpinnerEstudio.getValue() : (int) spinnerDescanso.getValue();
        tiempoRestante = minutos * 60;
    }

    private void actualizarTiempoDisplay() {
        int minutos = tiempoRestante / 60;
        int segundos = tiempoRestante % 60;
        labelTiempo.setText(String.format("%02d:%02d", minutos, segundos));
    }

    private void finalizarPeriodo() {
        timer.stop();
        enEjecucion = false;
        btnIniciar.setEnabled(true);
        btnPausar.setEnabled(false);

        String mensaje = modoEstudio ?
                "¡Tiempo de estudio completado! Toma un descanso." :
                "¡Descanso completado! Es hora de estudiar.";

        JOptionPane.showMessageDialog(this, mensaje, "Periodo Finalizado", JOptionPane.INFORMATION_MESSAGE);

        // Cambia automáticamente al siguiente modo
        cambiarModo(null);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerEstudio;
    private javax.swing.JButton btnCambiarModo;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescanso;
    private javax.swing.JLabel labelEstudio;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JSpinner spinnerDescanso;
    // End of variables declaration//GEN-END:variables
}
