/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.diccionario_de_conceptos;

/**
 *
 * @author Nicolas Marin
 */
public class Diccionario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Diccionario.class.getName());
    
    //Variables---------!
    
    String texto;
    int p=31;
    int m=997;
    int assix;
            

    /**
     * Creates new form Diccionario
     */
    public Diccionario() {
        initComponents();
    }
    
    private int hashing(){
            int longitud = texto.length();
            Integer hash_value = 0;
            for(int i = 0; i < longitud;i++){
                assix = texto.charAt(i);
                int power = (int)(Math.pow(p, i));
                hash_value = (hash_value + (assix * power));
    }
            return hash_value % m;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListCatalogo = new javax.swing.JList<>();
        BotonBuscar = new javax.swing.JToggleButton();
        LabelBuscar = new javax.swing.JLabel();
        ButtonNuevo = new javax.swing.JButton();
        TextBoxBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(70, 130, 169));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 580));

        ListCatalogo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(ListCatalogo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 260, 330));

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        LabelBuscar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        LabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBuscar.setText("Buscar concepto");
        getContentPane().add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 240, -1));

        ButtonNuevo.setText("Nuevo concepto");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, -1));

        TextBoxBuscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextBoxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(TextBoxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextBoxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxBuscarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
        
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Diccionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonBuscar;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JList<String> ListCatalogo;
    private javax.swing.JTextField TextBoxBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
