
package com.seitasks.encuesta;

import javax.swing.ButtonModel;
import java.time.LocalDateTime; // Import the LocalDateTime class
import java.time.format.DateTimeFormatter; // Import the DateTimeFormatter class
import javax.swing.JFrame;
/**
 *
 * @author Nicolas Marin
 */
public class Encuesta extends javax.swing.JPanel {

    /**
     * Creates new form Encuesta
     */
    
    Integer contador = 1;
    Integer productivo = 0;
    Integer metas = 0;
    Integer satisfecho = 0;
    Integer metodo = 0;
    Integer estres = 0;
    Integer programa = 0;
    String hora;
    
    
    public int Seleccion(){
        Integer aux = null;
        ButtonModel selectedModel = Respuestas.getSelection();
                if (selectedModel != null) {
                    if (Valor1.getModel() == selectedModel) {
                        aux=1;

                    } else if (Valor2.getModel() == selectedModel) {
                        aux = 2;

                    } else if (Valor3.getModel() == selectedModel) {
                        aux = 3;
                    } else if (Valor4.getModel() == selectedModel) {
                        aux = 4;
                    } else if (Valor5.getModel() == selectedModel) {
                        aux = 5;
                    }
                } else {
                    aux = 6;
                }
    return aux;
    }
       
    

    public Encuesta(int uso) {
        initComponents();
        programa = uso;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Respuestas = new javax.swing.ButtonGroup();
        Backgruond = new javax.swing.JPanel();
        LabelPregunta = new javax.swing.JLabel();
        DecoracionInferior = new javax.swing.JPanel();
        Valor5 = new javax.swing.JRadioButton();
        Valor4 = new javax.swing.JRadioButton();
        Valor3 = new javax.swing.JRadioButton();
        Valor2 = new javax.swing.JRadioButton();
        Valor1 = new javax.swing.JRadioButton();
        BotonSiguiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 720));

        Backgruond.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelPregunta.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        LabelPregunta.setText("Responde la encuesta");

        DecoracionInferior.setBackground(new java.awt.Color(255, 102, 102));
        DecoracionInferior.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout DecoracionInferiorLayout = new javax.swing.GroupLayout(DecoracionInferior);
        DecoracionInferior.setLayout(DecoracionInferiorLayout);
        DecoracionInferiorLayout.setHorizontalGroup(
            DecoracionInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DecoracionInferiorLayout.setVerticalGroup(
            DecoracionInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Respuestas.add(Valor5);
        Valor5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Valor5.setText("5");
        Valor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor5ActionPerformed(evt);
            }
        });

        Respuestas.add(Valor4);
        Valor4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Valor4.setText("3");
        Valor4.setBorder(Valor1.getBorder());
        Valor4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Valor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor4ActionPerformed(evt);
            }
        });

        Respuestas.add(Valor3);
        Valor3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Valor3.setText("4");
        Valor3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Valor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor3ActionPerformed(evt);
            }
        });

        Respuestas.add(Valor2);
        Valor2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Valor2.setText("2");
        Valor2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Valor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor2ActionPerformed(evt);
            }
        });

        Respuestas.add(Valor1);
        Valor1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Valor1.setText("1");
        Valor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor1ActionPerformed(evt);
            }
        });

        BotonSiguiente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.setBorder(null);
        BotonSiguiente.setBorderPainted(false);
        BotonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DecoracionInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(Backgruond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Valor4)
                            .addComponent(LabelPregunta)
                            .addComponent(Valor5)
                            .addComponent(Valor2)
                            .addComponent(BotonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Valor1)
                            .addComponent(Valor3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgruond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(LabelPregunta)
                .addGap(45, 45, 45)
                .addComponent(Valor5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Valor3)
                .addGap(11, 11, 11)
                .addComponent(Valor4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Valor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Valor1)
                .addGap(18, 18, 18)
                .addComponent(BotonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(DecoracionInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Valor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor5ActionPerformed

    private void Valor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor4ActionPerformed

    private void Valor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor3ActionPerformed

    private void Valor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor2ActionPerformed

    private void Valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valor1ActionPerformed

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
    Integer respuesta;
    respuesta = Seleccion();  
       switch (contador) {
     case 0 -> LabelPregunta.setText("Responde la encuesta");
     case 1 -> {
         LabelPregunta.setText("¿Qué tan productivo te sentiste?");
         BotonSiguiente.setText("Siguiente");
         productivo = respuesta;
            }
    case 2 -> {
        LabelPregunta.setText("¿Que tanto sientes que alcanzaste tus metas de estudio en esta sesión?");
        metas = respuesta;
            }
    case 3 -> {
        LabelPregunta.setText("¿Qué tan satisfecho estas con tus resultados?");
        BotonSiguiente.setText("Siguiente");
        satisfecho =respuesta;
            }
    case 4 -> {
        LabelPregunta.setText("¿Qué tanta importancia le das al método de estudio por tus resultados?");
        BotonSiguiente.setText("Siguiente");
        metodo = respuesta;
            }
    case 5 -> {
        LabelPregunta.setText("¿Qué nivel de estrés experimentaste durante esta sesión de estudio?");
        BotonSiguiente.setText("Finalizar");
        estres = respuesta;
            }
    case 6 -> {
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("HH:mm");
        hora = myDateObj.format(myFormatObj);
        Escritor.escribirResultados(productivo, metas, satisfecho, metodo, estres,hora,programa);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
            }
    default -> LabelPregunta.setText("Error critico la ventana no se cerro");
  }
       contador++;
    }//GEN-LAST:event_BotonSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgruond;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JPanel DecoracionInferior;
    private javax.swing.JLabel LabelPregunta;
    private javax.swing.ButtonGroup Respuestas;
    private javax.swing.JRadioButton Valor1;
    private javax.swing.JRadioButton Valor2;
    private javax.swing.JRadioButton Valor3;
    private javax.swing.JRadioButton Valor4;
    private javax.swing.JRadioButton Valor5;
    // End of variables declaration//GEN-END:variables
}
