/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.seitasks.FlashCards;
import com.seitasks.encuesta.MainEncuesta;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FalshCardWindow extends javax.swing.JPanel {
    
    private LinkedList<Flashcard> listaFlashcards = new LinkedList<>();
    private ArrayList<Flashcard> arrayFlashcards = new ArrayList<>();
    private int indiceActual = -1;
    private static final String ARCHIVO_DATOS = "flashcards.dat";
    
    public FalshCardWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        FlashCardAdd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Preguntatxt = new javax.swing.JTextField();
        Respuestatxt = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ShowFlashcard = new javax.swing.JPanel();
        Pregunta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PreguntatxtArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RespuestatxtArea = new javax.swing.JTextArea();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 360));

        Background.setBackground(new java.awt.Color(248, 244, 239));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlashCardAdd.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Flash Card");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pregunta:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Respuesta:");

        Preguntatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntatxtActionPerformed(evt);
            }
        });

        Respuestatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestatxtActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(51, 0, 51));
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Agregar");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FlashCardAddLayout = new javax.swing.GroupLayout(FlashCardAdd);
        FlashCardAdd.setLayout(FlashCardAddLayout);
        FlashCardAddLayout.setHorizontalGroup(
            FlashCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlashCardAddLayout.createSequentialGroup()
                .addGroup(FlashCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlashCardAddLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(FlashCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Preguntatxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Respuestatxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(FlashCardAddLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(FlashCardAddLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(FlashCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlashCardAddLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );
        FlashCardAddLayout.setVerticalGroup(
            FlashCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlashCardAddLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Preguntatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Respuestatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        Background.add(FlashCardAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 200, 380));

        ShowFlashcard.setBackground(new java.awt.Color(0, 0, 0));
        ShowFlashcard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pregunta.setBackground(new java.awt.Color(51, 0, 51));

        PreguntatxtArea.setBackground(new java.awt.Color(204, 204, 204));
        PreguntatxtArea.setColumns(20);
        PreguntatxtArea.setRows(5);
        jScrollPane1.setViewportView(PreguntatxtArea);

        javax.swing.GroupLayout PreguntaLayout = new javax.swing.GroupLayout(Pregunta);
        Pregunta.setLayout(PreguntaLayout);
        PreguntaLayout.setHorizontalGroup(
            PreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        PreguntaLayout.setVerticalGroup(
            PreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        ShowFlashcard.add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 390, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));

        RespuestatxtArea.setColumns(20);
        RespuestatxtArea.setRows(5);
        jScrollPane2.setViewportView(RespuestatxtArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        ShowFlashcard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 390, 110));

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        ShowFlashcard.add(Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        ShowFlashcard.add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        Background.add(ShowFlashcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void configurarEventos() {
        Add.addActionListener(e -> agregarTarjeta());
        Anterior.addActionListener(e -> mostrarPrevious());
        Siguiente.addActionListener(e -> mostrarNext());
    }
    private void saveFlashcards() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(ARCHIVO_DATOS))) {
            oos.writeObject(listaFlashcards);
        } catch (IOException e) {
            System.err.println("Error saving: " + e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    private void loadFlashcards() {
        File archivo = new File(ARCHIVO_DATOS);
        if (!archivo.exists()) return;

        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(ARCHIVO_DATOS))) {
            listaFlashcards = (LinkedList<Flashcard>) ois.readObject();
            
            arrayFlashcards.clear();
            Node<Flashcard> currentNode = listaFlashcards.Head;
            while (currentNode != null) {
                arrayFlashcards.add(currentNode.Dato);
                currentNode = currentNode.nextNode;
            }
            
            if (!arrayFlashcards.isEmpty()) {
                indiceActual = 0;
                mostrarCard(indiceActual);
            }
            
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Error loading: " + e.getMessage());
        }
    }
    private void agregarTarjeta() {
        String pregunta = Preguntatxt.getText().trim();
        String respuesta = Respuestatxt.getText().trim();
        
        if (pregunta.isEmpty() || respuesta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Complete ambos campos", 
                "Campos vacíos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Flashcard nuevaTarjeta = new Flashcard(pregunta, respuesta);
        listaFlashcards.add(nuevaTarjeta);
        arrayFlashcards.add(nuevaTarjeta);

        saveFlashcards();

        Preguntatxt.setText("");
        Respuestatxt.setText("");

        if (arrayFlashcards.size() == 1) {
            indiceActual = 0;
            mostrarCard(indiceActual);
        }
        
        updateButtons();
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Flashcard agregada exitosamente", 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    private void mostrarCard(int index) {
        if (index >= 0 && index < arrayFlashcards.size()) {
            Flashcard fc = arrayFlashcards.get(index);
            PreguntatxtArea.setText(fc.getPregunta());
            RespuestatxtArea.setText(fc.getRespuesta());
        } else {
            PreguntatxtArea.setText("");
            RespuestatxtArea.setText("");
        }
        updateButtons();
    }
    private void mostrarPrevious() {
        if (indiceActual > 0) {
            indiceActual--;
            mostrarCard(indiceActual);
        }
    }
    private void mostrarNext() {
        if (indiceActual < arrayFlashcards.size() - 1) {
            indiceActual++;
            mostrarCard(indiceActual);
        }
    }
     private void updateButtons() {
        boolean hayTarjetas = !arrayFlashcards.isEmpty();
        Anterior.setEnabled(hayTarjetas && indiceActual > 0);
        Siguiente.setEnabled(hayTarjetas && indiceActual < arrayFlashcards.size() - 1);
    }
    private void RespuestatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestatxtActionPerformed
        agregarTarjeta();
    }//GEN-LAST:event_RespuestatxtActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        mostrarNext();
    }//GEN-LAST:event_SiguienteActionPerformed

    private void PreguntatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntatxtActionPerformed
        Respuestatxt.requestFocus();
    }//GEN-LAST:event_PreguntatxtActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        agregarTarjeta();
    }//GEN-LAST:event_AddActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        mostrarPrevious();
    }//GEN-LAST:event_AnteriorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int response = JOptionPane.showConfirmDialog(
            this,
            "¿Quieres registrar tu sesión?",
            "Registrar Sesión",
            JOptionPane.YES_NO_OPTION
        );
        
        if (response == JOptionPane.YES_OPTION) {
            MainEncuesta.main(1);
        } else if (response == JOptionPane.NO_OPTION) {
            javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        }         
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Anterior;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel FlashCardAdd;
    private javax.swing.JPanel Pregunta;
    private javax.swing.JTextField Preguntatxt;
    private javax.swing.JTextArea PreguntatxtArea;
    private javax.swing.JTextField Respuestatxt;
    private javax.swing.JTextArea RespuestatxtArea;
    private javax.swing.JPanel ShowFlashcard;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
